# Generated by Django 4.2.6 on 2023-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_description_listing_sold_listing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='type',
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Disques', 'Records'), ('Vetements', 'Clothing'), ('Affiches', 'Posters'), ('Divers', 'Miscellaneous')], default='Disques', max_length=20),
            preserve_default=False,
        ),
    ]
