# Generated by Django 4.2.6 on 2023-11-24 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_type_listing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='description',
        ),
        migrations.RemoveField(
            model_name='band',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='band',
            name='year',
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
